//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoConsula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.Segmentos = new HashSet<Segmento>();
        }
    
        public int IdT_Curso { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Id_CursoRequisito { get; set; }
        public bool Autorizado { get; set; }
        public int IdF_Pais { get; set; }
        public Nullable<int> NotaMinima { get; set; }
        public bool Visible { get; set; }
        public string IdF_UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string IdF_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public bool Estado { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Segmento> Segmentos { get; set; }
    }
}
