//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoConsula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prueba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prueba()
        {
            this.Respuestas = new HashSet<Respuesta>();
            this.Resultados = new HashSet<Resultado>();
        }
    
        public int IdT_Prueba { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public int Intentos { get; set; }
        public bool Aleatorio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta> Respuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultado> Resultados { get; set; }
    }
}
