//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoConsula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respuesta()
        {
            this.Resultados = new HashSet<Resultado>();
        }
    
        public int IdT_Respuesta { get; set; }
        public int IdF_Pregunta { get; set; }
        public int IdF_Prueba { get; set; }
        public string IdF_Usuario { get; set; }
        public string TituloRespuesta { get; set; }
        public string TextoRespuesta { get; set; }
        public bool Correcto { get; set; }
        public decimal Ponderacion { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Pregunta Pregunta { get; set; }
        public virtual Prueba Prueba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultado> Resultados { get; set; }
    }
}
