//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoConsula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segmento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Segmento()
        {
            this.Contenidos = new HashSet<Contenido>();
        }
    
        public int IdT_Segmento { get; set; }
        public int IdF_Curso { get; set; }
        public Nullable<int> Id_SegmentoPadre { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public bool Visible { get; set; }
        public int IdF_Pais { get; set; }
    
        public virtual Curso Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contenido> Contenidos { get; set; }
    }
}
